INSERT INTO diario_diario(nombre,url,imagen) VALUES ('El Comercio',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('La República',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('Perú 21',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('Gestión',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('Correo Semanal (lunes)',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('Caretas (jueves)',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('Hildebrandt en sus Trece (viernes)',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('Correo',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('Diario 16',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('La Primera',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('Expreso',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('La Razón',null,null);
INSERT INTO diario_diario(nombre,url,imagen) VALUES ('El Peruano',null,null);